mimir:
  gateway:
    ingress:
      hosts:
        - host: metrics-monitoring.suxess.demo-peaknetworks.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: mimir-nginx-tls
          hosts:
            - metrics-monitoring.suxess.demo-peaknetworks.com
