teams:

# new team stanza for team kubrix
  - name: kubrix
    sourceRepos:
      - 'https://github.com/bob-kubrix-demo/kubrix-*'
    clusterResourceWhitelist:
      - group: ""
        kind: Namespace
      - group: kargo.akuity.io
        kind: Project
    appOfAppsRepo:
      repoURL: https://github.com/bob-kubrix-demo/kubrix-apps
      path: .
      revision: main
    multiStageKargoAppSet:
      github:
        organization: bob-kubrix-demo
