falco:
  falcosidekick:
    webui:
      ingress:
        hosts:
          - host: falco.suxess.demo-peaknetworks.com
            paths:
              - path: /
                pathType: Prefix
        tls:
            - secretName: falco-server-tls
              hosts:
                - falco.suxess.demo-peaknetworks.com